""" Pim Logo Challenge """
def main():
    """ Main function """
    print("windows")
    print("starbucks coffee")
    print("google")
    print("java")
    print("apple")
    print("mozilla firefox")
    print("sublime text")
    print("google chrome")
    print("python")
    print("microsoft edge")
    print("skype")
    print("twitter")
    print("youtube")
    print("line")
    print("messenger")
    print("instagram")
    print("intel")
    print("kickstarter")
    print("nvidia")
    print("android")
    print("kentucky fried chicken")
    print("mcdonald's")
    print("micro-star international")
    print("the sims 4 get together")
    print("ubuntu")

main()
